### PR TITLE
Add support for passing additional IFD metadata to encodeImage

### PR DESCRIPTION
**Pull request by Scimonster**

### CODE REVIEW

**Comment by photopea** [comment]
Does anybody actually need it? I am not a fan of blindly adding functionality, just to have more code.

**Comment by Scimonster** [comment]
I would like to be able to set at the very least the DPI (t282, t283, t296) of the generated TIFFs.

I can imagine others may want to set the date (t306) or artist (t315) of their images.

**Comment by photopea** [comment]
I think you will never need to actually save anything as a TIFF.

**Comment by photopea** [comment]
I am sorry for sounding rude. But if we decide to go this way, we may start implementing advanced TIFF encoder with many different modes and compressions, and with 5x more complex interface and 5x more code, 90 percent of which nobody will ever use.

If you really need to save DPI, date or artist, prepare the necessary input for the "encode()" funciton.

**Comment by Scimonster** [comment]
We've been through this already in #11. I have a real business requirement to save as TIFF, ideally with 600 dpi.

While compression would also be nice, i agree that it is too much code for too little benefit. But this is just 5 lines.

If it were possible to use the `encode()` function for this i would, but i don't see a way to add extra tags without rewriting the `encodeImage()` function.

**Comment by photopea** [comment]
Ok, add your extra parameter, but don't mention it in docs. I don't want to encourage people to use TIFFs.

**Comment by Scimonster** [comment]
Why are you so against saving as TIFF?

If it was just for me, i would simply fork and add the feature. But the point of bringing it here is so that others can benefit as well, so i feel it's only fair to mention it in the docs.

**Comment by photopea** [comment]
All you save in TIFFs can be saved in PNGs. PNG has much nicer and simpler structure. I am against using unnecessarily many formats, when they don't have any benefits compared to each other. Aren't you glad, that the web starts to use UTF8 instead of other text encodings? If somebody creates UTF8 to Windows-1251 , it should be considered as a crime against humanity :D  Same for PNG to TIFF converter.

**Comment by photopea** [comment]
Or imagine some company to make a smartphone, ignoring MicroUSB and creating their own charging connector with their own chargers.  I don't care what image format or what charging connector is used among people. But I want it to be a single format, because if everybody uses their own format, it makes the life harder.

**Comment by Scimonster** [comment]
But despite our best efforts to move forwards, there are always those with legacy requirements. 

Like it or not, [iconv-lite](https://www.npmjs.com/package/iconv-lite), a package for converting between text encodings, including UTF8 to Windows-1251, is one of the most popular packages on npm.

> Or imagine some company to make a smartphone, ignoring MicroUSB and creating their own charging connector with their own chargers.

\*cough\*Apple\*cough\*

**Comment by photopea** [comment]
I agree, that we can not fix the whole world. But let's not give people a chance to make it more complicated (by letting them encode TIFFs).  I made UTIF.js to help people get rid of "legacy" and convert all their images to more regular formats. Not to create even more TIFFs.

**Comment by Scimonster** [comment]
A quick Google search reveals several articles from the past few years that still recommend TIFF as an optimal format.
[1][1] [2][2] [3][3] [4][4] [5][5]
TIFFs can have higher resolution than PNG can.

Admittedly the web is heavily biased towards PNG over TIFF, but JavaScript isn't only for the web anymore.

---

Anyways, shall we merge this PR as-is? Leave the metadata in the docs so people who need it can discover it?

[1]: https://www.peernet.com/why-use-tiff-who-uses-tiff/
[2]: https://www.peernet.com/why-use-tiff/
[3]: http://www.smartimage.com/whats-the-difference-between-gif-png-jpeg-and-tiff/
[4]: https://www.scanyourentirelife.com/tiff-vs-png-file-format-hurt-save-scanned-photos/
[5]: https://photo.stackexchange.com/questions/13893/is-tiff-really-of-higher-quality-than-png-24

**Comment by photopea** [comment]
Your first two articles are from company, which makes TIFF software. They probably made that software in 80s and still want to sell it. Other articles just repeat the positves of TIFF from the time, when there was no PNG. Note, that you can have 16-bits images in PNG.  **TIFFs do not have any advantages over PNGs.**. Not even a resolution.

I suggest you to create an advanced TIFF encoder locally, on top of UTIF.js (make your own local version of encodeImage() ).

**Comment by mn4367** [comment]
> All you save in TIFFs can be saved in PNGs.

> TIFFs do not have any advantages over PNGs.

Sorry to revive this closed thread, but the two statements are simply wrong. As much as I would like to burry a bunch of image formats too and as much as I like PNG, TIFF simply cannot be replaced today by PNG. That doesn't mean, that UTIF has to support anything from TIFF, but TIFF is still far more versatile than PNG. Just a few examples:

- How do you store multiple b/w pages in a single file? With TIFF it's common to store 
  scanned multipage documents in a single file. Also used in almost any FAX application.
- If your printer asks you to send print ready CMYK images, can you store that in PNG?
- If your publisher asks you to send lossless files from your latest photo reportage with 
  complete IPTC/EXIF metadata, can you do that with PNG?

These are *not* exotic use cases, they happen probably a million times every day.

**Comment by Scimonster** [comment]
For anyone who needs this feature it is available in my fork. [Scimonster/UTIF.js](/Scimonster/UTIF.js)

**Comment by photopea** [comment]
@mn4367  I disagree with you.

* you can't just say, that it is always better to store multiple images in a single file. Sometimes, it is better to store them separately, or put them into a ZIP archive. It depends on a users taste.
* there is no such thing as CMYK or RGB colors. Each image must have defined a color space, or to be equipped with a color profile. There are many RGB or CMYK color spaces and color conversion is almost always necessary before sending an image to a printer or to a display. In PNG, you can define the color profile and then convert it to other color spaces. The CMYK colors, that the printer requires, may be completely different colors (different color space), than the CMYK that is used in a TIFF file. Converting colors from other spaces (e.g. from sRGB) to a printers color space is the basic thing, that the printer interface should be able to do.
* I don't know, what exactly do you wish to store in EXIF metadata. But PNG allows you to store things like time, name of the author, name of the software, parameters of the camera and many others.

@Scimonster  let's add this extra parameter for encodeImage. Can you please make a new pull request?
But please, don't implement other features, until you actually need them.

**Comment by Scimonster** [comment]
We can just reopen the PR without making a new one.

You agree now to include the parameter and include it in the docs?

**Comment by mn4367** [comment]
> - you can't just say, that it is always better to store multiple images in a single file. Sometimes, it is better to store them separately, or put them into a ZIP archive. It depends on a users taste.

I didn't say that it is better in general but there are enough use cases/customers where it is needed. And a scanned document is much easier to handle in a single file than in multiple files. You don't extract single pages form PDFs and store them separately in a ZIP, don't you ;-)

> - there is no such thing as CMYK or RGB colors.

Sure [there is](https://en.wikipedia.org/wiki/CMYK_color_model). And I wasn't talking about the device on your desk, I was talking about the real guy who puts your work on real paper. They normally use 4 colors (again, real wet colors in physical machines) cyan, magenta, yellow and black. And this is exactly what a CMYK-TIFF file contains, a layer/channel for all 4 colors. This has nothing to do with color profiles. Of course the printer house/design studio will most probably apply a color profile specific to the printing machine or the paper used in it, but the original file is in CMYK, not RGB or anything else. And you can't store that in a standard way in PNG.

> - I don't know, what exactly do you wish to store in EXIF metadata. But PNG allows you to store things like time, name of the author, name of the software, parameters of the camera and many others.

I know that there are ways to store just anything/something in PNG in ancillary chunks. But according to [this source](https://en.wikipedia.org/wiki/Exif) it isn't standardized. And which software is able to read Exif in PNG? Is there a written real standard? How about storing a thumbnail? By the way, if PNG fits everything, why do Camera makers don't use it to store their raw data?

Again, I just wanted to show some use cases where it is impossible to use PNG. That doesn't mean that PNG is bad. Nor is TIFF. PNG was mainly made to replace GIF and to display image data on display devices. That's fine. TIFF was conceived and extended over time to be a universal container for many different use cases of storing images of all kinds. That's also fine.

But TIFF cannot be replaced by PNG today. At least not without compromises/lack of functionality/loss of data/ loss of convenience/loss of standardization/"name yours".

**Comment by photopea** [comment]
* CMYK / RGB : what you are talking are just additive / subtractive color models in general. You can store colors in both and none of them has any advantage over the other. What I am trying to say is, that if you say RGB 255,0,0 does not have to be red. Also CMYK 1,1,1,1 does not have to be black. You can never take numbers form a TIFF or PNG file and print them directly. Which means, that there is no advantage in storing an image in some CMYK profile (as you can do in TIFF), over storing it using in some RGB profile (as you do in PNG) I feel stupid for having to explain it. 

What is not standardized is TIFF. The official standard does not mention "JPEG extensions", which are very frequent. Many companies extened TIFF in their own ways. There is no software, that can open "any tiff".

I am not saying, that PNG fits everything. I just say, that it is **possible** more comfortable to store the equivalent data in much simpler formats which are properly standardized (like PNG or JPG) than in TIFF.

**Comment by mn4367** [comment]
> RGB 255,0,0 does not have to be red

What is it then? If it isn't red then it has to be specified somewhere how to handle it. Does PNG cover that?

> Also CMYK 1,1,1,1 does not have to be black.

Sorry, nobody would use that. If you would print this the result will be muddy and the printer would probably demand a proper file. 

> You can never take numbers form a TIFF or PNG file and print them directly.

In the case of CMYK you can/should (almost). The correct value for black in CMYK is 0,0,0,1 not 1,1,1,1. It tells you exactly that you have to use black ink and only black ink here. If you don't, you'd be ignoring what CMYK was created for. CMYK is *not* just a different color model, it's directly connected to a physical printing process, that's why it is still used.

The traditional (and still used today) workflow in a printer house is often something like this: Make a color separation of the CMYK-data, that results in a 1Bit bitmap for each 4 colors. Print each bitmap to a physical b/w film. Based on this film a printing plate is colored with this color in a specific raster angle. This is done with all 4 colors and all of them are printed in order to the paper. RGB wasn't created for this workflow even if you somehow stuff a different RGB interpretation hint into a PNG (which would be non standard?). The Wikipedia article states that color conversions never go without losses, there is no easy conversion between RGB and CMYK. And the K is missing in PNG. You can't substitute the K in PNG without a deviation from the current standard, or am I missing something?

I remember the days when you proudly showed up in a design studio with your Windows Truecolor BMP and asked for it to be put into a brochure and printed. All you gained was rolling eyes because nobody used RBG in a serious design/printing workflow. Nevertheless I *do* have to admit that nowadays things have changed/got easier with all the digital printing lanes, but CMYK is still in use/demanded and valid.

> Which means, that there is no advantage in storing an image in some CMYK profile (as you can do in TIFF), over storing it in some RGB profile (as you do in PNG).

There is, printing, see above. I think you can't ignore that. Otherwise you'd be saying that everybody using CMYK is/has been probably following the wrong route. What about CIE L\*a\*b\*? It's becoming more and more popular in image processing and it is something completely different. TIFF can store that, PNG can't.

> What is not standardized is TIFF.

Difficult. TIFF is also known as *T*housand *I*ncompatible *F*ile *F*ormats. Maybe there is no single standard (although TIFF 6.0 from Adobe could be seen like that) but some extensions are even ISO standards and RFCs and Exif is covered by that. This can be seen as a curse or a benefit. Some people need an extensible format for special purposes. They don't have to reinvent the wheel and can use/extend TIFF. But I'm quite sure that a lot of them won't be able to use PNG because it's too restricted (which is an advantage in a limited number of use cases).

> But let's not give people a chance to make it more complicated (by letting them encode TIFFs). I made UTIF.js to help people get rid of "legacy" and convert all their images to more regular formats. Not to create even more TIFFs.

Please don't get me wrong, I'd prefer to use PNG too and I really appreciate your library and your work, thank you very much! But I think it's not OK to try to "force/push" people to use a format by refusing to implement* basic features in a TIFF library when PNG is not (yet) a complete or almost complete alternative.

Anyway, maybe we should stop arguing. What about thinking about a different approach, for example completely separate decoding and encoding into two libraries where the encoding library could be based on a plugin mechanism for writing different TIFF variants?

*No, Im of course not demanding that you implement anything in your library, I just couldn't follow the reasons.

**Comment by photopea** [comment]
I am sorry, but you don't understand colours.

You can not print CMYK values from the TIFF directly on any printer. Each printer may use (chemically) different inks. Two different printers may need different amounts (ratio) of C/M/Y/K to print the same color. The same is true for RGB and monitors - you can not display RGB values on a monitor directly, because the may look different. That is why color profiles have been invented.

Please read at least first pages of this http://www.color.org/specification/ICC1v43_2010-12.pdf  to learn basics.

**Comment by mn4367** [comment]
Again, I wasn't talking about the printer on your desk, I was talking about printing in a printer company aka offset printing: https://en.wikipedia.org/wiki/Offset_printing, especially the first paragraph of "Modern offset printing". Or maybe [here](http://www.fastprint.co.uk/blog/cmyk-vs-rgb-printing-what-is-the-difference-when-designing.html) or [here](http://www.printernational.org/rgb-versus-cmyk.php). Anyway I'm out.

**Comment by photopea** [comment]
I was not talking about a printer on your desk either. Different printers use different inks (or different color technology in general), no matter what is the size or the cost of a printer. The articles, that you attached, seem to be written by authors, which know even less than any of us.

In modern days (after inventing color profiles), it really does not matter if you store your image in RGB, CMYK or some other (e.g. 100 channel format, which uses combinations of 100 different colors), as long as your file is equipped with a color profile.

**Pull request merged**
