### PR TITLE
add getMetaData function

### PR DESCRIPTION
**Pull request by manticorp**
add a getMetaData functionality

### CODE REVIEW

**Comment by photopea** [comment]
What about just giving the Boolean parameter to UTIF.decode(), whether the image should be decoded too?  Or an array of tags, that should be skipped.

**Comment by Scimonster** [comment]
If you go the route of passing parameters to `UTIF.decode()`, please support a Boolean for metadata. The user shouldn't have to pass the tags.

**Comment by photopea** [comment]
I use this library for parsing TIFF images, [DNG images](https://en.wikipedia.org/wiki/Digital_Negative) and EXIF metadata in other files (with no image). I guess the Boolean tag (decode / not decode image) should be enough. What do you think @manticorp  ?  

Or we colud split decode() into two steps: decode() would just read tags, and decodeImage() will take tags and decode the image.

Again, regular images are usually small and decoding them whole does not take too much extra performance or memory. So you will probably be the only one using this feature.

**Comment by manticorp** [comment]
I prefer the idea of splitting into two functions. 

Passing a parameter could get confusing if you ever decide to add another parameter to the function, as deciding on behaviour would be logically complex. 

Keep responsibility of the function low, each function should only do one thing.

**Comment by photopea** [comment]
Ok, I did it, see the new README.

**Pull request closed without merging**
