### PR TITLE
Extract function to render the tiff image

### PR DESCRIPTION
**Pull request by na-ka-na**
We're using a UI library to preview images, but don't have access to the img element.

Verified that this approach works for us if we use the UTIF.renderIMG function

### CODE REVIEW

**Comment by photopea** [comment]
That is a great idea! I did it in my own pull request, it is called UTIF.bufferToURI(buff) :)

**Comment by na-ka-na** [comment]
> That is a great idea! I did it in my own pull request, it is called UTIF.bufferToURI(buff) :)

Cool! any idea when it'll be part of a release?

**Comment by photopea** [comment]
It is already there, I released it before writing my comment. Use UTIF from here, not from NPM.

**Comment by TheOptik** [comment]
Are there any plans on releasing this to NPM?

**Comment by photopea** [comment]
I never used NPM. Could you release it on NPM?

**Pull request closed without merging**
